# Generated by Django 4.2.7 on 2025-12-29 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acts', '0002_act_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTreeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_acts', models.IntegerField(default=0, help_text='Total acts submitted by user')),
                ('total_decorations', models.IntegerField(default=0, help_text='Total decorations on tree')),
                ('tree_level', models.IntegerField(default=1, help_text='Current tree level (1-5)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text="User's tree progress", on_delete=django.db.models.deletion.CASCADE, related_name='tree_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreeDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoration_type', models.CharField(choices=[('ornament', 'Ornament'), ('star', 'Star'), ('light', 'Light'), ('garland', 'Garland'), ('gift', 'Gift'), ('snowflake', 'Snowflake')], default='ornament', help_text='Type of decoration', max_length=20)),
                ('position_x', models.FloatField(help_text='X position on tree (0-100 percentage)')),
                ('position_y', models.FloatField(help_text='Y position on tree (0-100 percentage)')),
                ('color', models.CharField(default='#DC2626', help_text='Color of decoration (hex code)', max_length=20)),
                ('size', models.FloatField(default=1.0, help_text='Size scale factor (0.5 to 2.0)')),
                ('is_auto_placed', models.BooleanField(default=True, help_text='Whether decoration was auto-placed or manually positioned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocked_by_act', models.ForeignKey(blank=True, help_text='Act that unlocked this decoration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_decorations', to='acts.act')),
                ('user', models.ForeignKey(help_text='User who owns this decoration', on_delete=django.db.models.deletion.CASCADE, related_name='tree_decorations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'decoration_type'], name='tree_treede_user_id_61cb3f_idx'), models.Index(fields=['user', 'created_at'], name='tree_treede_user_id_6d1fcf_idx')],
            },
        ),
    ]
