# Generated by Django 4.2.7 on 2025-12-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the act of kindness')),
                ('category', models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('time', 'Time/Volunteer'), ('money', 'Money'), ('other', 'Other')], help_text='Category of the act', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9)),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100)),
                ('country', models.CharField(blank=True, help_text='Country name', max_length=100)),
                ('evidence_url', models.URLField(blank=True, help_text='Optional evidence/photo URL', null=True)),
                ('submitted_by', models.CharField(blank=True, help_text='Name of submitter (optional)', max_length=100)),
                ('is_anonymous', models.BooleanField(default=True, help_text='Whether submission is anonymous')),
                ('appreciation_count', models.IntegerField(default=0, help_text='Number of appreciations/likes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='acts_act_latitud_b60562_idx'), models.Index(fields=['category'], name='acts_act_categor_74521f_idx'), models.Index(fields=['created_at'], name='acts_act_created_0be0c5_idx'), models.Index(fields=['city'], name='acts_act_city_949ca6_idx')],
            },
        ),
    ]
